# Refer smarthome.ipynb dataset for data cleansing

### Loading cleansed dataset

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv('C:\\projects\\ml\\0.datasets\\smarthomedatasets\\homedataset.csv')
df.head()

Unnamed: 0  use [kW]  gen [kW]  House overall [kW]  Dishwasher [kW]  \
0           0  0.932833  0.003483            0.932833         0.000033   
1           1  0.934333  0.003467            0.934333         0.000000   
2           2  0.931817  0.003467            0.931817         0.000017   
3           3  1.022050  0.003483            1.022050         0.000017   
4           4  1.139400  0.003467            1.139400         0.000133   

   Furnace 1 [kW]  Furnace 2 [kW]  Home office [kW]  Fridge [kW]  \
0        0.020700        0.061917          0.442633     0.124150   
1        0.020717        0.063817          0.444067     0.124000   
2        0.020700        0.062317          0.446067     0.123533   
3        0.106900        0.068517          0.446583     0.123133   
4        0.236933        0.063983          0.446533     0.122850   

   Wine cellar [kW]  ...  visibility  apparentTemperature  pressure  \
0          0.006983  ...        10.0                29.26   1016.91   
1          0.006983  ...        10.0                29.26   1016.91   
2          0.006983  ...        10.0                29.26   1016.91   
3          0.006983  ...        10.0                29.26   1016.91   
4          0.006850  ...        10.0                29.26   1016.91   

   windSpeed  windBearing  precipIntensity  dewPoint  summary  icon  \
0       9.18        282.0              0.0      24.4        3     1   
1       9.18        282.0              0.0      24.4        3     1   
2       9.18        282.0              0.0      24.4        3     1   
3       9.18        282.0              0.0      24.4        3     1   
4       9.18        282.0              0.0      24.4        3     1   

   precipProbability  
0                0.0  
1                0.0  
2                0.0  
3                0.0  
4                0.0  

[5 rows x 31 columns]

In [5]:
df.drop(columns = "Unnamed: 0", inplace = True)
df.head()

use [kW]  gen [kW]  House overall [kW]  Dishwasher [kW]  Furnace 1 [kW]  \
0  0.932833  0.003483            0.932833         0.000033        0.020700   
1  0.934333  0.003467            0.934333         0.000000        0.020717   
2  0.931817  0.003467            0.931817         0.000017        0.020700   
3  1.022050  0.003483            1.022050         0.000017        0.106900   
4  1.139400  0.003467            1.139400         0.000133        0.236933   

   Furnace 2 [kW]  Home office [kW]  Fridge [kW]  Wine cellar [kW]  \
0        0.061917          0.442633     0.124150          0.006983   
1        0.063817          0.444067     0.124000          0.006983   
2        0.062317          0.446067     0.123533          0.006983   
3        0.068517          0.446583     0.123133          0.006983   
4        0.063983          0.446533     0.122850          0.006850   

   Garage door [kW]  ...  visibility  apparentTemperature  pressure  \
0          0.013083  ...        10.0                29.26   1016.91   
1          0.013117  ...        10.0                29.26   1016.91   
2          0.013083  ...        10.0                29.26   1016.91   
3          0.013000  ...        10.0                29.26   1016.91   
4          0.012783  ...        10.0                29.26   1016.91   

   windSpeed  windBearing  precipIntensity  dewPoint  summary  icon  \
0       9.18        282.0              0.0      24.4        3     1   
1       9.18        282.0              0.0      24.4        3     1   
2       9.18        282.0              0.0      24.4        3     1   
3       9.18        282.0              0.0      24.4        3     1   
4       9.18        282.0              0.0      24.4        3     1   

   precipProbability  
0                0.0  
1                0.0  
2                0.0  
3                0.0  
4                0.0  

[5 rows x 30 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503910 entries, 0 to 503909
Data columns (total 30 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   use [kW]             503910 non-null  float64
 1   gen [kW]             503910 non-null  float64
 2   House overall [kW]   503910 non-null  float64
 3   Dishwasher [kW]      503910 non-null  float64
 4   Furnace 1 [kW]       503910 non-null  float64
 5   Furnace 2 [kW]       503910 non-null  float64
 6   Home office [kW]     503910 non-null  float64
 7   Fridge [kW]          503910 non-null  float64
 8   Wine cellar [kW]     503910 non-null  float64
 9   Garage door [kW]     503910 non-null  float64
 10  Kitchen 12 [kW]      503910 non-null  float64
 11  Kitchen 14 [kW]      503910 non-null  float64
 12  Kitchen 38 [kW]      503910 non-null  float64
 13  Barn [kW]            503910 non-null  float64
 14  Well [kW]            503910 non-null  float64
 15  Microwave [kW]   

In [7]:
df

use [kW]  gen [kW]  House overall [kW]  Dishwasher [kW]  \
0       0.932833  0.003483            0.932833         0.000033   
1       0.934333  0.003467            0.934333         0.000000   
2       0.931817  0.003467            0.931817         0.000017   
3       1.022050  0.003483            1.022050         0.000017   
4       1.139400  0.003467            1.139400         0.000133   
...          ...       ...                 ...              ...   
503905  1.601233  0.003183            1.601233         0.000050   
503906  1.599333  0.003233            1.599333         0.000050   
503907  1.924267  0.003217            1.924267         0.000033   
503908  1.978200  0.003217            1.978200         0.000050   
503909  1.990950  0.003233            1.990950         0.000050   

        Furnace 1 [kW]  Furnace 2 [kW]  Home office [kW]  Fridge [kW]  \
0             0.020700        0.061917          0.442633     0.124150   
1             0.020717        0.063817          0.444067     0.124000   
2             0.020700        0.062317          0.446067     0.123533   
3             0.106900        0.068517          0.446583     0.123133   
4             0.236933        0.063983          0.446533     0.122850   
...                ...             ...               ...          ...   
503905        0.085267        0.642417          0.041783     0.005267   
503906        0.104017        0.625033          0.041750     0.005233   
503907        0.422383        0.637733          0.042033     0.004983   
503908        0.495667        0.620367          0.042100     0.005333   
503909        0.494700        0.634133          0.042100     0.004917   

        Wine cellar [kW]  Garage door [kW]  ...  visibility  \
0               0.006983          0.013083  ...       10.00   
1               0.006983          0.013117  ...       10.00   
2               0.006983          0.013083  ...       10.00   
3               0.006983          0.013000  ...       10.00   
4               0.006850          0.012783  ...       10.00   
...                  ...               ...  ...         ...   
503905          0.008667          0.013483  ...        8.74   
503906          0.008433          0.013433  ...        8.74   
503907          0.008467          0.012933  ...        8.74   
503908          0.008233          0.012817  ...        8.74   
503909          0.008133          0.012833  ...        8.74   

        apparentTemperature  pressure  windSpeed  windBearing  \
0                     29.26   1016.91       9.18        282.0   
1                     29.26   1016.91       9.18        282.0   
2                     29.26   1016.91       9.18        282.0   
3                     29.26   1016.91       9.18        282.0   
4                     29.26   1016.91       9.18        282.0   
...                     ...       ...        ...          ...   
503905                29.45   1011.49       6.72        186.0   
503906                29.45   1011.49       6.72        186.0   
503907                29.45   1011.49       6.72        186.0   
503908                29.45   1011.49       6.72        186.0   
503909                29.45   1011.49       6.72        186.0   

        precipIntensity  dewPoint  summary  icon  precipProbability  
0                0.0000     24.40        3     1               0.00  
1                0.0000     24.40        3     1               0.00  
2                0.0000     24.40        3     1               0.00  
3                0.0000     24.40        3     1               0.00  
4                0.0000     24.40        3     1               0.00  
...                 ...       ...      ...   ...                ...  
503905           0.0101     31.27       10     6               0.51  
503906           0.0101     31.27       10     6               0.51  
503907           0.0101     31.27       10     6               0.51  
503908           0.0101     31.27       10     6               0.51  
503909           0

### Split the data into x and y i.e features and targets

In [8]:
y = df.iloc[:,-1].values
x = df.iloc[:,0:29].values
x,y

(array([[9.32833333e-01, 3.48333300e-03, 9.32833333e-01, ...,
         2.44000000e+01, 3.00000000e+00, 1.00000000e+00],
        [9.34333333e-01, 3.46666700e-03, 9.34333333e-01, ...,
         2.44000000e+01, 3.00000000e+00, 1.00000000e+00],
        [9.31816667e-01, 3.46666700e-03, 9.31816667e-01, ...,
         2.44000000e+01, 3.00000000e+00, 1.00000000e+00],
        ...,
        [1.92426667e+00, 3.21666700e-03, 1.92426667e+00, ...,
         3.12700000e+01, 1.00000000e+01, 6.00000000e+00],
        [1.97820000e+00, 3.21666700e-03, 1.97820000e+00, ...,
         3.12700000e+01, 1.00000000e+01, 6.00000000e+00],
        [1.99095000e+00, 3.23333300e-03, 1.99095000e+00, ...,
         3.12700000e+01, 1.00000000e+01, 6.00000000e+00]]),
 array([0.  , 0.  , 0.  , ..., 0.51, 0.51, 0.51]))

### Now split the dataset into training and testing

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((377932, 29), (125978, 29), (377932,), (125978,))

### Scaling the data in the range 0 to 1

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [11]:
x_train_sc = sc.fit_transform(x_train)

In [12]:
x_test_sc = sc.transform(x_test)

In [13]:
x_train.shape,x_test_sc.shape

((377932, 29), (125978, 29))

In [14]:
y

array([0.  , 0.  , 0.  , ..., 0.51, 0.51, 0.51])

## Applying Machine Learning Algortithms

## Linear Regression

In [15]:
from sklearn.linear_model import LinearRegression


### For Unscaled Data

In [16]:
lr = LinearRegression()
lr.fit(x_train,y_train)
train_lr_acc = lr.score(x_train,y_train)
test_lr_acc = lr.score(x_test,y_test)
print("Training Accuracy for unscaled dataset: ",train_lr_acc)
print("Testing Accuracy for unscaled dataset: ",test_lr_acc)

Training Accuracy for unscaled dataset:  0.7886976288615848
Testing Accuracy for unscaled dataset:  0.7901053306838769


### For Scaled Data

In [17]:
lr1 = LinearRegression()
lr1.fit(x_train_sc,y_train)
train_lr_sc_acc = lr1.score(x_train_sc,y_train)
test_lr_sc_acc = lr1.score(x_test_sc,y_test)
print("Training Accuracy for scaled dataset: ",train_lr_sc_acc)
print("Testing Accuracy for scaled dataset: ",test_lr_sc_acc)

Training Accuracy for scaled dataset:  0.7886976347027401
Testing Accuracy for scaled dataset:  0.7901054965513852


## Decision Tree Regressor

In [18]:
from sklearn.tree import DecisionTreeRegressor

### For Unscaled Data

In [19]:
dtc = DecisionTreeRegressor()
dtc.fit(x_train,y_train)
train_dtc_acc = dtc.score(x_train,y_train)
test_dtc_acc = dtc.score(x_test,y_test)
print("Training Accuracy for unscaled dataset: ",train_dtc_acc)
print("Testing Accuracy for unscaled dataset: ",test_dtc_acc)

Training Accuracy for unscaled dataset:  1.0
Testing Accuracy for unscaled dataset:  0.9999998272171434


### For Scaled Data

In [20]:
dtc1 = DecisionTreeRegressor()
dtc1.fit(x_train_sc,y_train)
train_dtc_sc_acc = dtc1.score(x_train_sc,y_train)
test_dtc_sc_acc = dtc1.score(x_test_sc,y_test)
print("Training Accuracy for unscaled dataset: ",train_dtc_sc_acc)
print("Testing Accuracy for unscaled dataset: ",test_dtc_sc_acc)

Training Accuracy for unscaled dataset:  1.0
Testing Accuracy for unscaled dataset:  0.9999998272171434


## Random Forest Regression

In [21]:
from sklearn.ensemble import RandomForestRegressor


### For Unscaled Data

In [22]:
rfc = RandomForestRegressor()
rfc.fit(x_train,y_train)
train_rfc_acc = rfc.score(x_train,y_train)
test_rfc_acc = rfc.score(x_test,y_test)
print("Training Accuracy for unscaled dataset: ",train_rfc_acc)
print("Testing Accuracy for unscaled dataset: ",test_rfc_acc)

Training Accuracy for unscaled dataset:  0.9999999911811993
Testing Accuracy for unscaled dataset:  0.9999998656872464


### For Scaled Data

In [23]:
rfc1 = RandomForestRegressor()
rfc1.fit(x_train_sc,y_train)
train_rfc_sc_acc = rfc1.score(x_train_sc,y_train)
test_rfc_sc_acc = rfc1.score(x_test_sc,y_test)
print("Training Accuracy for unscaled dataset: ",train_rfc_sc_acc)
print("Testing Accuracy for unscaled dataset: ",test_rfc_sc_acc)

Training Accuracy for unscaled dataset:  0.9999999919620757
Testing Accuracy for unscaled dataset:  0.999999866689387


## Support Vector Machine Regressor

In [24]:
from sklearn.svm import SVR

### For Unscaled Data

In [ ]:
# svm = SVR()
# svm.fit(x_train,y_train)
# train_svm_acc = svm.score(x_train,y_train)
# test_svm_acc = svm.score(x_test,y_test)
# print("Training Accuracy for unscaled dataset: ",train_svm_acc)
# print("Testing Accuracy for unscaled dataset: ",test_svm_acc)

### For Scaled Data

In [26]:
svm1 = SVR()
svm1.fit(x_train_sc,y_train)
train_svm_sc_acc = svm1.score(x_train_sc,y_train)
test_svm_sc_acc = svm1.score(x_test_sc,y_test)
print("Training Accuracy for unscaled dataset: ",train_svm_sc_acc)
print("Testing Accuracy for unscaled dataset: ",test_svm_sc_acc)

Training Accuracy for unscaled dataset:  0.904261625431864
Testing Accuracy for unscaled dataset:  0.9028561313678564
